### ISSUE TITLE
AttributeError: 'module' object has no attribute 'grammar'

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/nl_robot_console#12]
```
Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/nl_robot_console/src/nl_robot_console/console.py", line 283, in <module>
    sys.exit(main())
  File "/home/amigo/ros/kinetic/system/src/nl_robot_console/src/nl_robot_console/console.py", line 270, in main
    repl = REPL("challenge_gpsr", debug=debug)
  File "/home/amigo/ros/kinetic/system/src/nl_robot_console/src/nl_robot_console/console.py", line 61, in __init__
    self._load_grammar()
  File "/home/amigo/ros/kinetic/system/src/nl_robot_console/src/nl_robot_console/console.py", line 85, in _load_grammar
    self.parser = cfgparser.CFGParser.fromstring(self.knowledge.grammar)
AttributeError: 'module' object has no attribute 'grammar'
```

**Comment by rokusottervanger** [comment]
Are you up to date and do you have robotics_testlabs specified as the current environment?

**Comment by rokusottervanger** [comment]
This is fixed by now
